server:
  port:  8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jamesshow/spring-cloud-conf-store
          #username: root
          #passphrase: 1234
          search-paths:
            - '*service'